const mongoose = require('mongoose');

const propertyModel = require('../Model/propertyModel');

// connect to database

mongoose.set('strictQuery', true);

mongoose.connect("mongodb://localhost:27017/bham-choice", { useNewUrlParser: true }, { useUnifiedTopology: true }, (err) => {
    if (err) {
        console.log(err);
    } else {
        console.log("I'm connected to the database")
    }
})

const addPropertyList = async () => {

    try {

        await propertyModel.deleteMany({}).lean()

        const propertyToAdd = await propertyModel.insertMany([

            {
                propertyId: "somr101",
                advertType: "social housing",
                type: "house",
                address: "15a malvin road",
                town: "selly oak",
                postcode: "b29 3sk",
                bedRoom: "3", 
                bathRoom: "1", 
                reception: "yes",
                cTaxBand: "c", 
                tenancyType: "shorthold",
                availableFrom: "2nd week of next month", 
                furnished: "no", 
                parking: "roadside",
                garage: "no",
                garden: "yes", 
                patio: "yes",
                floor: "0", 
                kitchenFitted: "yes",
                deposit: "900.00", 
                fees: "75.00",
                rent: "900.00",
                pets: "no",
                imageUrl: "https://cdn.images.express.co.uk/img/dynamic/51/590x/council-houses-1517950.webp?r=1636326653098",
                comments: "There is an initial porch entrance, entrance hallway, lounge, modern kitchen diner with patio doors, downstairs w/c, three bedrooms and modern family bathroom. The property furhter benefits from a spacious driveway and large rear patio garden. The property is ideally located for both Northfield Town Centre, Northfield Train Station and has links to the Queen Elizabeth Hospital and Birmingham University. The deposit payable is £900.00 We have been advised by the owner that the property council tax is band is C.",
                dateRecorded: new Date(),
            },
            {
                propertyId: "wemr102",
                advertType: "social housing",
                address: "310 world end road",
                type: "house",
                town: "bearwood",
                postcode: "b66 4na",
                bedRoom: "3", 
                bathRoom: "2", 
                reception: "2",
                cTaxBand: "a", 
                tenancyType: "shorthold",
                availableFrom: "1nd week of next month", 
                furnished: "yes", 
                parking: "roadside",
                garage: "no",
                garden: "yes", 
                patio: "yes",
                floor: "0", 
                kitchenFitted: "yes",
                deposit: "900.00", 
                fees: "75.00",
                rent: "1100.00", 
                pets: "yes",
                imageUrl:"https://ichef.bbci.co.uk/news/976/cpsprodpb/4FA1/production/_110958302_broomhillbristol.jpg.webp",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "srhw103",
                advertType: "social housing",
                type: "maisonette",
                address: "510 sommerset road",
                town: "handsworth",
                postcode: "b19 1he",
                bedRoom: "3", 
                bathRoom: "2", 
                reception: "2",
                cTaxBand: "a", 
                tenancyType: "shorthold",
                availableFrom: "1nd week of next month", 
                furnished: "yes", 
                parking: "roadside",
                garage: "no",
                garden: "yes", 
                patio: "yes",
                floor: "0", 
                kitchenFitted: "yes",
                deposit: "950.00", 
                fees: "75.00",
                rent: "950.00", 
                pets: "yes",
                imageUrl:"https://assets.publishing.service.gov.uk/government/uploads/system/uploads/image_data/file/79780/s300_New_build_social_housing_-_Warwick_CC_960x640.jpg",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "gcst105",
                advertType: "affordable rent",
                type: "flat",
                address: "199 great colmor street, city center",
                town: "birmingham",
                postcode: "b15 2by",
                bedRoom: "1", 
                bathRoom: "1", 
                reception: "1",
                cTaxBand: "d", 
                tenancyType: "shorthold",
                availableFrom: "3nd week of next month", 
                furnished: "yes", 
                parking: "roadside and garage",
                garage: "yes",
                garden: "no", 
                patio: "no",
                floor: "2", 
                kitchenFitted: "yes",
                deposit: "750.00", 
                fees: "75.00",
                rent: "750.00", 
                pets: "no",
                imageUrl:"https://cdn.images.express.co.uk/img/dynamic/51/590x/secondary/tower-block-council-3744270.webp?r=1636326658154",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "cbbt105",
                advertType: "affordable rent",
                type: "flat",
                address: "cleverdale building, bristol street, city center",
                town: "birmingham",
                postcode: "b5 7az",
                bedRoom: "1", 
                bathRoom: "1", 
                reception: "1",
                cTaxBand: "d", 
                tenancyType: "shorthold",
                availableFrom: "immediately", 
                furnished: "yes", 
                parking: "underground reserved parking space",
                garage: "no",
                garden: "no", 
                patio: "no",
                floor: "3", 
                kitchenFitted: "yes",
                deposit: "750.00", 
                fees: "75.00",
                rent: "750.00", 
                pets: "no",
                imageUrl:"https://assets.publishing.service.gov.uk/government/uploads/system/uploads/image_data/file/17016/s300_social-housing-960x640.jpg",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "srs106",
                advertType: "social housing",
                type: "bungalow",
                address: "4500 stratford road",
                town: "solihul",
                postcode: "b90 4ae",
                bedRoom: "4", 
                bathRoom: "2", 
                reception: "2",
                cTaxBand: "d", 
                tenancyType: "shorthold",
                availableFrom: "immediately", 
                furnished: "yes", 
                parking: "in-front parking space",
                garage: "yes",
                garden: "big garden", 
                patio: "no",
                floor: "0", 
                kitchenFitted: "yes",
                deposit: "750.00", 
                fees: "75.00",
                rent: "1250.00", 
                pets: "yes",
                imageUrl:"https://i2-prod.birminghammail.co.uk/incoming/article18901189.ece/ALTERNATES/s615b/1_TRMRMMGLPICT000020823126.jpg",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "drs107",
                advertType: "social housing",
                type: "flat",
                address: "1a dell road",
                town: "solihul",
                postcode: "b90 4bc",
                bedRoom: "2", 
                bathRoom: "1", 
                reception: "1",
                cTaxBand: "d", 
                tenancyType: "shorthold",
                availableFrom: "immediately", 
                furnished: "no", 
                parking: "in-front parking space",
                garage: "no",
                garden: "no", 
                patio: "no",
                floor: "2", 
                kitchenFitted: "yes",
                deposit: "750.00", 
                fees: "75.00",
                rent: "1000.00", 
                pets: "yes",
                imageUrl:"https://www.ft.com/__origami/service/image/v2/images/raw/http%3A%2F%2Fcom.ft.imagepublish.upp-prod-eu.s3.amazonaws.com%2F9ec49f9a-8768-11e4-bc7c-00144feabdc0?dpr=1&fit=scale-down&source=next&width=700",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "cspb108",
                advertType: "social housing",
                type: "maisonette",
                address: "carsile street",
                town: "perry barr",
                postcode: "b42 1aa",
                bedRoom: "2", 
                bathRoom: "2", 
                reception: "2",
                cTaxBand: "d", 
                tenancyType: "shorthold",
                availableFrom: "2nd week of next month", 
                furnished: "no", 
                parking: "in-front parking space",
                garage: "yes",
                garden: "big garden", 
                patio: "no",
                floor: "0", 
                kitchenFitted: "yes",
                deposit: "850.00", 
                fees: "75.00",
                rent: "850.00", 
                pets: "yes",
                imageUrl:"https://cdn.rt.emap.com/wp-content/uploads/sites/4/2020/03/21044558/goldsmithsjimstephenson7-2.jpg",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "msse109",
                advertType: "affordable rent",
                type: "flat",
                address: "1145 shard end close",
                town: "shard end",
                postcode: "b34 6ne",
                bedRoom: "1", 
                bathRoom: "1", 
                reception: "1",
                cTaxBand: "a", 
                tenancyType: "shorthold",
                availableFrom: "4nd week of next month", 
                furnished: "no", 
                parking: "roadside",
                garage: "no",
                garden: "no", 
                patio: "no",
                floor: "1", 
                kitchenFitted: "yes",
                deposit: "650.00", 
                fees: "75.00",
                rent: "650.00", 
                pets: "no",
                imageUrl:"https://upload.wikimedia.org/wikipedia/commons/a/aa/Golden_Lane_Estate_-_geograph.org.uk_-_1404919.jpg",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "assc110",
                advertType: "social housing",
                type: "flat",
                address: "155c albert street",
                town: "sutton coldfield",
                postcode: "b23 5az",
                bedRoom: "1", 
                bathRoom: "1", 
                reception: "1",
                cTaxBand: "a", 
                tenancyType: "shorthold",
                availableFrom: "4nd week of next month", 
                furnished: "no", 
                parking: "roadside",
                garage: "no",
                garden: "no", 
                patio: "no",
                floor: "3", 
                kitchenFitted: "yes",
                deposit: "750.00", 
                fees: "75.00",
                rent: "750.00", 
                pets: "no",
                imageUrl:"https://labmonline.co.uk/wp-content/uploads/2018/08/SHGP-Roundup-pic-2.jpg",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "lsfh111",
                advertType: "affordable rent",
                type: "other",
                address: "10 livery street",
                town: "foxhollies",
                postcode: "b28 8rz",
                bedRoom: "3", 
                bathRoom: "2", 
                reception: "2",
                cTaxBand: "c", 
                tenancyType: "shorthold",
                availableFrom: "4nd week of next month", 
                furnished: "yes", 
                parking: "in-front of house and roadside",
                garage: "no",
                garden: "yes", 
                patio: "no",
                floor: "0", 
                kitchenFitted: "yes",
                deposit: "1150.00", 
                fees: "75.00",
                rent: "1100.00", 
                pets: "no",
                imageUrl:"https://www.domesticsurveys.co.uk/wp-content/uploads/sites/1007/2019/07/SAM_3808-1-1030x687.jpg.webp",
                comments: "none",
                dateRecorded: new Date(),
            },
            {
                propertyId: "wsfg112",
                advertType: "affordable rent",
                type: "other",
                address: "56 wharf street",
                town: "fox and goose",
                postcode: "b8 2aw",
                type: "semi detached",
                bedRoom: "2", 
                bathRoom: "1", 
                reception: "2",
                cTaxBand: "d", 
                tenancyType: "shorthold",
                availableFrom: "2nd week of next month", 
                furnished: "yes", 
                parking: "in-front of house and roadside",
                garage: "no",
                garden: "yes", 
                patio: "no",
                floor: "0", 
                kitchenFitted: "yes",
                deposit: "950.00", 
                fees: "75.00",
                rent: "950.00", 
                pets: "no",
                imageUrl:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/ParkwayHousesSeacroft.jpg/800px-ParkwayHousesSeacroft.jpg",
                comments: "none",
                dateRecorded: new Date(),
            },
        ])

        console.log("The collection of ClientJoint has been recreated in the database", propertyToAdd);


    } catch (err) {
        console.log(err)
    }
}

addPropertyList();

setTimeout(function () { mongoose.connection.close(); }, 10000);  // Close mongoose connection after 10sec
